version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
  loyaltyservice:
    container_name: loyaltyservice
    image: loyaltyservice
    restart: always
    ports:
      - 8050:8050
    volumes:
      - .:/app/LoyaltyService
  reservationservice:
    container_name: reservationservice
    image: reservationservice
    restart: always
    ports:
      - 8070:8070
    volumes:
      - .:/app/ReservationService
  paymentservice:
    container_name: paymentservice
    image: paymentservice
    restart: always
    ports:
      - 8060:8060
    volumes:
      - .:/app/PaymentService
  gatewayservice:
    container_name: gatewayservice
    image: gatewayservice
    restart: always
    ports:
      - 8080:8080
    volumes:
      - .:/app/Gatewayservice
volumes:
  db-data:
